### ISSUE TITLE
Firing function on elementScrolledIntoView question

### ISSUE THREAD

**Issue by jcourtice-zz** [inorganik/angular-scroll-spy#1]
Hey...so I'm relatively new to angular (and javascript) and I'm trying to use this to fire a function on scroll but I can't get it to work. I'm using Angular Seed and I've got this code in my controller: 

```
$scope.$on('elementFirstScrolledIntoView', function (event, data) {
            if (data === '#scroll-spy-test') {
                console.log('hey')
            }
        });
```

Am I missing something?

**Comment by inorganik** [comment]
remove the `#`
