### ISSUE TITLE
Disable coma

### ISSUE THREAD

**Issue by Cclleemm** [inorganik/angular-scroll-spy#2]
Hello,
is it possible to use it without coma "," ?

I would write "16853" instead of "16,853".

Thank's

**Comment by inorganik** [comment]
You're thinking of https://github.com/inorganik/countUp.js

Yes you can - in the options object, pass `false` as the value for `useGrouping`. If you would like more info please read the README on the countUp repo.

**Comment by Cclleemm** [comment]
Thank you !
